name: Auto Bot Post Generator

on:
  schedule:
    - cron: '0 8 * * *'  # Executa todo dia às 08:00 UTC (05:00 da manhã no Brasil)
  workflow_dispatch:  # Permite executar manualmente

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependências (se houver)
      run: pip install -r requirements.txt || true

    - name: Executar bot.py
      run: python bot.py

    - name: Commit e push dos arquivos atualizados
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add posts.json
        git commit -m "Atualização automática: novos posts" || echo "Nada para commitar"
        git push

